Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/runezvdw/virtualenv/store.innovestraenterprises.co.ke/3.13/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'store.innovestraenterprises.co.ke'. You may need to add 'store.innovestraenterprises.co.ke' to ALLOWED_HOSTS.
